/**
 * image-provenance.ts
 *
 * Server-side image metadata management for 2026 AI transparency standards.
 *
 * Implements:
 *   - IPTC Digital Source Type (https://www.iptc.org/std/photometadata/specification/)
 *   - GPS / sensitive EXIF scrubbing for organic (original) photography
 *   - Schema.org ImageObject helpers for SEO structured data
 *
 * Used by the `media` collection's `beforeChange` hook in payload.config.ts.
 */

import os from 'os'
import path from 'path'
import fs from 'fs'
import { exiftool } from 'exiftool-vendored'

// ---------------------------------------------------------------------------
// IPTC Digital Source Type URIs
// https://cv.iptc.org/newscodes/digitalsourcetype/
// ---------------------------------------------------------------------------
const IPTC_DST = {
  /** Original photography -- no algorithmic generation involved */
  organic: undefined, // No IPTC override; strip GPS instead
  /** A composite blending original capture with AI-generated elements */
  enhanced: 'http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia',
  /** Fully synthetic image generated by a trained model */
  generated: 'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia',
} as const

export type GenerationType = keyof typeof IPTC_DST

// ---------------------------------------------------------------------------
// EXIFTool tags to remove for organic images (privacy / GDPR compliance)
// ---------------------------------------------------------------------------
const PRIVACY_TAGS_TO_CLEAR = [
  'GPS*',          // All GPS positioning tags
  'CameraSerialNumber',
  'LensSerialNumber',
  'SerialNumber',
  'BodySerialNumber',
  'InternalSerialNumber',
  'MakerNote',     // Vendor-specific block often containing serial / location data
]

// ---------------------------------------------------------------------------
// Core metadata processor
// ---------------------------------------------------------------------------

/**
 * Processes image metadata in-place on a temporary file copy.
 *
 * @param sourcePath  Absolute path to the image file on disk.
 * @param type        The declared generation type.
 * @returns           The path to the processed file (callers must clean up).
 */
export async function processImageMetadata(
  sourcePath: string,
  type: GenerationType,
): Promise<string> {
  // Security: reject any path containing traversal sequences before touching fs
  const resolved = path.resolve(sourcePath)
  const tmpDir = os.tmpdir()
  const mediaDir = path.resolve(process.cwd(), 'media')

  const relTmp = path.relative(tmpDir, resolved)
  const isInTmp = !relTmp.startsWith('..') && !path.isAbsolute(relTmp)

  const relMedia = path.relative(mediaDir, resolved)
  const isInMedia = !relMedia.startsWith('..') && !path.isAbsolute(relMedia)

  if (!isInTmp && !isInMedia) {
    throw new Error(
      `image-provenance: Rejected suspicious file path outside of allowed directories: ${resolved}`,
    )
  }

  // Work on a temporary copy so the original is untouched until we are done
  const ext = path.extname(resolved)
  const tmpOut = path.join(tmpDir, `payload-img-${Date.now()}-processed${ext}`)
  fs.copyFileSync(resolved, tmpOut)

  try {
    if (type === 'organic') {
      // Strip GPS and serial number tags for privacy compliance.
      // exiftool supports glob patterns for tag names (e.g. GPS*).
      const wipeArgs = PRIVACY_TAGS_TO_CLEAR.map((tag) => `-${tag}=`)
      await exiftool.write(tmpOut, {}, { writeArgs: [...wipeArgs, '-overwrite_original'] })
    } else if (type === 'enhanced' || type === 'generated') {
      const digitalSourceType = IPTC_DST[type]!
      // exiftool supports namespaced XMP tags (e.g. 'XMP-iptcExt:DigitalSourceType')
      // at runtime, but exiftool-vendored's WriteTags interface does not enumerate
      // all namespaced variants. Cast through unknown to satisfy TypeScript.
      await exiftool.write(
        tmpOut,
        {
          // IPTC Core field (XMP namespace preferred by modern readers)
          'XMP-iptcExt:DigitalSourceType': digitalSourceType,
          // Legacy IPTC-IIM By-line for maximum compatibility with older readers
          'IPTC:By-lineTitle': 'AI-Assisted',
        } as unknown as import('exiftool-vendored').WriteTags,
        { writeArgs: ['-overwrite_original'] },
      )
    }
  } catch (err) {
    // Non-fatal: log and return the unmodified copy.
    // This prevents upload failures when exiftool cannot parse an exotic format.
    console.error('[image-provenance] exiftool write failed, proceeding with unmodified file:', err)
  }

  return tmpOut
}

/**
 * Reads back the processed file as a Buffer and removes the temp copy.
 */
export async function readAndClean(tmpPath: string): Promise<Buffer> {
  const buf = fs.readFileSync(tmpPath)
  try {
    fs.unlinkSync(tmpPath)
  } catch {
    // Best-effort cleanup; OS will reclaim on reboot if this fails
  }
  return buf
}

// ---------------------------------------------------------------------------
// Schema.org SEO utility
// ---------------------------------------------------------------------------

export type GenerationTypeMeta = {
  /** Schema.org ImageObject `license` URL for the IPTC Digital Source Type */
  digitalSourceType: string | null
  /** Schema.org `acquireLicensePage` — points to the IPTC CV entry */
  acquireLicensePage: string | null
  /** Prefix prepended to `alt` text to signal provenance to screen readers */
  altPrefix: string
  /** Human-readable label shown in the admin panel */
  label: string
}

const GENERATION_TYPE_META: Record<GenerationType, GenerationTypeMeta> = {
  organic: {
    digitalSourceType: null,
    acquireLicensePage: null,
    altPrefix: '',
    label: 'Organic (Original Photography)',
  },
  enhanced: {
    digitalSourceType: IPTC_DST.enhanced!,
    acquireLicensePage: 'https://www.iptc.org/std/photometadata/specification/',
    altPrefix: '[AI Enhanced] ',
    label: 'AI Enhanced (Hybrid)',
  },
  generated: {
    digitalSourceType: IPTC_DST.generated!,
    acquireLicensePage: 'https://www.iptc.org/std/photometadata/specification/',
    altPrefix: '[AI Generated] ',
    label: 'AI Generated (Synthetic)',
  },
}

/**
 * A minimal shape for a hydrated Payload media document as returned by the
 * local API or REST endpoint (at depth >= 0).
 */
export interface MediaDoc {
  id: string | number
  url?: string | null
  width?: number | null
  height?: number | null
  alt?: string | null
  generationType?: GenerationType | null
}

/**
 * Returns Schema.org `ImageObject` properties for use in JSON-LD structured
 * data, Next.js `<Image>` props, and `<meta>` tags.
 *
 * Usage in a Server Component:
 * ```ts
 * import { getImageSEOProperties } from '@/lib/image-provenance'
 *
 * const seo = getImageSEOProperties(mediaDoc)
 *
 * // In a JSON-LD script tag:
 * const imageObject = {
 *   "@type": "ImageObject",
 *   "url": seo.url,
 *   "name": seo.name,
 *   ...seo.schemaOrg,
 * }
 *
 * // As Image alt text:
 * <Image src={mediaDoc.url} alt={seo.accessibleAlt} ... />
 * ```
 */
export function getImageSEOProperties(mediaDoc: MediaDoc) {
  const type: GenerationType =
    (mediaDoc.generationType as GenerationType) ?? 'organic'
  const meta = GENERATION_TYPE_META[type] ?? GENERATION_TYPE_META.organic

  const rawAlt = mediaDoc.alt ?? ''
  const accessibleAlt = meta.altPrefix + rawAlt

  const schemaOrg: Record<string, string | number | null> = {
    '@type': 'ImageObject',
    contentUrl: mediaDoc.url ?? null,
    description: accessibleAlt,
  }

  if (mediaDoc.width) schemaOrg.width = mediaDoc.width
  if (mediaDoc.height) schemaOrg.height = mediaDoc.height
  if (meta.digitalSourceType) schemaOrg.digitalSourceType = meta.digitalSourceType
  if (meta.acquireLicensePage) schemaOrg.acquireLicensePage = meta.acquireLicensePage

  return {
    /** The image URL (pass directly to Next.js <Image src={...}>) */
    url: mediaDoc.url ?? null,
    /** Alt text with provenance prefix for screen readers */
    accessibleAlt,
    /** Raw alt text without prefix (for decorative or title uses) */
    rawAlt,
    /** Provenance label for display in UI (e.g., "AI Generated (Synthetic)") */
    label: meta.label,
    /** Full Schema.org ImageObject-compatible properties object for JSON-LD */
    schemaOrg,
    /** The resolved GenerationType (never null) */
    generationType: type,
  }
}
